// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG-GaxU5qcngjS_fuMpQRZiC2AukxuNLI',
    appId: '1:790768167109:web:57424bb2c320bc03d5a8ac',
    messagingSenderId: '790768167109',
    projectId: 'chatapp-50e5f',
    authDomain: 'chatapp-50e5f.firebaseapp.com',
    storageBucket: 'chatapp-50e5f.appspot.com',
    measurementId: 'G-LGSBVLVPVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD2MoutPhOkN3Q_uGGkksKJQ2J2_Xp83o',
    appId: '1:790768167109:android:48304d025b1335a0d5a8ac',
    messagingSenderId: '790768167109',
    projectId: 'chatapp-50e5f',
    storageBucket: 'chatapp-50e5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYPMgo7DnMY2J1-32I6x2CmpL8yvRKaxM',
    appId: '1:790768167109:ios:1ce7c0dcf69e8616d5a8ac',
    messagingSenderId: '790768167109',
    projectId: 'chatapp-50e5f',
    storageBucket: 'chatapp-50e5f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYPMgo7DnMY2J1-32I6x2CmpL8yvRKaxM',
    appId: '1:790768167109:ios:1ce7c0dcf69e8616d5a8ac',
    messagingSenderId: '790768167109',
    projectId: 'chatapp-50e5f',
    storageBucket: 'chatapp-50e5f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
